# Generated by Django 4.2.10 on 2024-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Catgories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
    ]
