# Generated by Django 4.2.10 on 2024-02-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0003_alter_category_options_remove_category_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogging.category",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogging.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(
                blank=True, through="blogging.PostCategory", to="blogging.post"
            ),
        ),
    ]
